<?xml version="1.0" encoding="Shift_JIS"?>
<?xml-stylesheet type="text/xsl" href="hoot.xsl"?>
<!DOCTYPE gamelist [
	<!ELEMENT gamelist (game|bind|childlists)*>
	<!ATTLIST gamelist date CDATA #IMPLIED>
	<!ELEMENT childlists (list)*>
	<!ELEMENT list (#PCDATA)>
	<!ELEMENT bind (exts,driver,options?)>
	<!ELEMENT exts (ext)*>
	<!ELEMENT ext (#PCDATA)>
	<!ELEMENT game (name,driver,driveralias?,options?,romlist?,titlelist?)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT driver (#PCDATA)>
	<!ATTLIST driver type CDATA #IMPLIED>
	<!ELEMENT driveralias (#PCDATA)>
	<!ATTLIST driveralias type CDATA #IMPLIED>
	<!ELEMENT options (option)*>
	<!ELEMENT option EMPTY>
	<!ATTLIST option name CDATA #REQUIRED
		 value CDATA #REQUIRED>
	<!ELEMENT romlist (rom)*>
	<!ATTLIST romlist archive CDATA #IMPLIED>
	<!ELEMENT rom (#PCDATA)>
	<!ATTLIST rom type CDATA #REQUIRED
		offset CDATA #IMPLIED>
	<!ELEMENT titlelist (title|range)*>
	<!ELEMENT title (#PCDATA)>
	<!ATTLIST title code CDATA #REQUIRED
					type CDATA #IMPLIED>
	<!ELEMENT range (#PCDATA)>
	<!ATTLIST range min CDATA #REQUIRED
					max CDATA #REQUIRED
					extcode CDATA #IMPLIED>
]>
<gamelist date="2005/09/25">
	<!-- //glodia -->
	<game>
		<name>[PC-88] Lyrane</name>
		<driver type="opn">pc88</driver>
		<driveralias type="PC-88">glodia</driveralias>
		<options>
			<option name="mdata_addr" value="0x0100"/>
			<option name="mdata_size" value="0x4e00"/>
			<option name="mfile_size" value="0x4e00"/>
		</options>
		<romlist archive="lyrane">
			<rom type="code" offset="0x0000">PATCH</rom>
			<rom type="code" offset="0x0100">OP</rom>
			<rom type="code" offset="0x5000">ED1</rom>
			<rom type="bgm" offset="0x00">OP</rom>
			<rom type="bgm" offset="0x01">GAME</rom>
			<rom type="bgm" offset="0x02">ED1</rom>
			<rom type="bgm" offset="0x03">ED2</rom>
		</romlist>
		<titlelist>
			<title code="0x00">オープニング</title>
			<title code="0x01">メインBGM</title>
			<title code="0x02">ゲームオーバー</title>
			<title code="0x03">エンディング</title>
		</titlelist>
	</game>
	<game>
		<name>[PC-88] Testament</name>
		<driver type="opn">pc88</driver>
		<driveralias type="PC-88">glodia</driveralias>
		<options>
			<option name="mdata_addr" value="0x4c00"/>
			<option name="use_vrtc" value="0x01"/>
		</options>
		<romlist archive="testamnt">
			<rom type="code" offset="0x0000">PATCH</rom>
			<rom type="code" offset="0x0100">INFO</rom>
			<rom type="bgm" offset="0x00">TS000</rom>
			<rom type="bgm" offset="0x01">TS001</rom>
			<rom type="bgm" offset="0x02">TS002</rom>
			<rom type="bgm" offset="0x03">TS003</rom>
			<rom type="bgm" offset="0x04">TS004</rom>
			<rom type="bgm" offset="0x05">TS005</rom>
			<rom type="bgm" offset="0x06">TS006</rom>
			<rom type="bgm" offset="0x07">TS007</rom>
			<rom type="bgm" offset="0x08">TS008</rom>
			<rom type="bgm" offset="0x09">TS009</rom>
			<rom type="bgm" offset="0x30">TS010</rom>
			<rom type="bgm" offset="0x31">TS011</rom>
		</romlist>
		<titlelist>
			<title code="0x80000000">オープニング</title>
			<title code="0x00000001">BGM 1</title>
			<title code="0x00000002">BGM 2</title>
			<title code="0x00000003">BGM 3</title>
			<title code="0x00000004">BGM 4</title>
			<title code="0x00000005">中ボスBGM</title>
			<title code="0x00000006">隠しステージBGM (Stage LSP &amp; RSP)</title>
			<title code="0x00000007">隠しステージBGM (Stage IDOL)</title>
			<title code="0x00000008">ペンタドラゴン</title>
			<title code="0x00000009">エンディング</title>
			<title code="0x80000030">ファンファーレ</title>
			<title code="0x80000031">ゲームオーバー</title>
		</titlelist>
	</game>
	<game>
		<name>[PC-88] Zavas (サバッシュ)</name>
		<driver type="opn">pc88</driver>
		<driveralias type="PC-88">glodia</driveralias>
		<options>
			<option name="mfile_size" value="0x2100"/>
			<option name="mdata_size" value="0x2100"/>
			<option name="use_vrtc"   value="0x01"/>
			<option name="clock_mul"  value="0x00"/>
		</options>
		<romlist archive="zavas">
			<rom type="code" offset="0x0000">PATCH</rom>
			<rom type="code" offset="0x0100">DRIVER</rom>
			<rom type="bgm" offset="0x00">ZAOP01</rom>
			<rom type="bgm" offset="0x01">ZAOP02</rom>
			<rom type="bgm" offset="0x02">ZABG01</rom>
			<rom type="bgm" offset="0x03">ZABG02</rom>
			<rom type="bgm" offset="0x04">ZABG03</rom>
			<rom type="bgm" offset="0x05">ZABG04</rom>
			<rom type="bgm" offset="0x06">ZABG05</rom>
			<rom type="bgm" offset="0x07">ZABG06</rom>
			<rom type="bgm" offset="0x08">ZABG07</rom>
			<rom type="bgm" offset="0x09">ZABG08</rom>
			<rom type="bgm" offset="0x0a">ZABG09</rom>
			<rom type="bgm" offset="0x0b">ZABG10</rom>
			<rom type="bgm" offset="0x0c">ZABG11</rom>
			<rom type="bgm" offset="0x0d">ZAOPBG</rom>
			<rom type="bgm" offset="0x0e">ZAFIGH</rom>
			<rom type="bgm" offset="0x0f">ZAED01</rom>
			<rom type="bgm" offset="0x10">ZAFIT2</rom>
			<rom type="bgm" offset="0x11">ZABIG</rom>
			<rom type="bgm" offset="0x12">ZASHOP</rom>
			<rom type="bgm" offset="0x13">ZACONG</rom>
			<rom type="bgm" offset="0x14">ZAMINA</rom>
			<rom type="bgm" offset="0x15">FAN1</rom>
			<rom type="bgm" offset="0x16">FAN3</rom>
			<rom type="bgm" offset="0x17">ZAGT01</rom>
			<rom type="bgm" offset="0x18">ZAGT02</rom>
		</romlist>
		<titlelist>
			<title code="0x80000000">サバッシュのテーマ (プロローグ)</title>
			<title code="0x80000001">サバッシュ メイン・タイトル(オープニング)</title>
			<title code="0x00000002">ファルガナ地方</title>
			<title code="0x00000003">ファルガナ城</title>
			<title code="0x00000004">カナートの財宝</title>
			<title code="0x00000005">アルフールの大要塞</title>
			<title code="0x00000006">カルムの塔</title>
			<title code="0x00000007">マラメイヤ地方</title>
			<title code="0x00000008">トマ村</title>
			<title code="0x00000009">ドルゲスタン大陸</title>
			<title code="0x0000000a">ドラゴン小国</title>
			<title code="0x0000000b">グールの館</title>
			<title code="0x0000000c">ブルバン要塞</title>
			<title code="0x0000000d">ダルゾン帝国</title>
			<title code="0x0000000e">モンスターバトル</title>
			<title code="0x8000000f">エンドタイトル (エンディング)</title>
			<title code="0x00000010">悲劇のテーマ</title>
			<title code="0x00000011">ファイナルシューティング</title>
			<title code="0x00000012">ショッピング</title>
			<title code="0x00000013">きずな</title>
			<title code="0x00000014">苦闘の果て</title>
			<title code="0x80000015">ファンファーレ1</title>
			<title code="0x80000016">ファンファーレ2</title>
			<title code="0x80000017">残念賞1</title>
			<title code="0x80000018">残念賞2</title>
		</titlelist>
	</game>
	<game>
		<name>[PC-98] Zavas (サバッシュ)</name>
		<driver type="opn">pc98vx</driver>
		<driveralias type="PC-98">glodia</driveralias>
		<options>
			<option name="bootcs" value="0x0060"/>
			<option name="bootip" value="0x0000"/>
			<option name="filesize" value="0x2200"/>
			<option name="dataaddr" value="0x22060"/>
			<option name="clockmul" value="0x04"/>
			<option name="datamax"  value="0x1a"/>
			<option name="fm_mix"   value="19"/>
			<option name="ssg_mix"  value="0"/>
    </options>
		<romlist archive="zavas98">
			<rom type="code" offset="0x00600">zavas98.bin</rom>
			<rom type="code" offset="0x10000">MAIN</rom>
			<rom type="bgm" offset="0x01">ZAOP01.S</rom>
			<rom type="bgm" offset="0x02">ZAOP02.S</rom>
			<rom type="bgm" offset="0x03">ZABG01.S</rom>
			<rom type="bgm" offset="0x04">ZABG02.S</rom>
			<rom type="bgm" offset="0x05">ZABG03.S</rom>
			<rom type="bgm" offset="0x06">ZABG04.S</rom>
			<rom type="bgm" offset="0x07">ZABG05.S</rom>
			<rom type="bgm" offset="0x08">ZABG06.S</rom>
			<rom type="bgm" offset="0x09">ZABG07.S</rom>
			<rom type="bgm" offset="0x0a">ZABG08.S</rom>
			<rom type="bgm" offset="0x0b">ZABG09.S</rom>
			<rom type="bgm" offset="0x0c">ZABG10.S</rom>
			<rom type="bgm" offset="0x0d">ZABG11.S</rom>
			<rom type="bgm" offset="0x0e">ZAOPBG.S</rom>
			<rom type="bgm" offset="0x0f">ZAFIGH.S</rom>
			<rom type="bgm" offset="0x10">ZAED01.S</rom>
			<rom type="bgm" offset="0x11">ZAFIT2.S</rom>
			<rom type="bgm" offset="0x12">ZABIG.S</rom>
			<rom type="bgm" offset="0x13">ZASHOP.S</rom>
			<rom type="bgm" offset="0x14">ZACONG.S</rom>
			<rom type="bgm" offset="0x15">ZAMINA.S</rom>
			<rom type="bgm" offset="0x16">ZAGT01.S</rom>
			<rom type="bgm" offset="0x17">ZAGT02.S</rom>
			<rom type="bgm" offset="0x18">FAN1.S</rom>
			<rom type="bgm" offset="0x19">FAN3.S</rom>
		</romlist>
		<titlelist>
			<title code="0x000001">サバッシュのテーマ (プロローグ)</title>
			<title code="0x000002">サバッシュ メイン・タイトル(オープニング)</title>
			<title code="0x010003">ファルガナ地方</title>
			<title code="0x010004">ファルガナ城</title>
			<title code="0x010005">カナートの財宝</title>
			<title code="0x010006">アルフールの大要塞</title>
			<title code="0x010007">カルムの塔</title>
			<title code="0x010008">マラメイヤ地方</title>
			<title code="0x010009">トマ村</title>
			<title code="0x01000a">ドルゲスタン大陸</title>
			<title code="0x01000b">ドラゴン小国</title>
			<title code="0x01000c">グールの館</title>
			<title code="0x01000d">ブルバン要塞</title>
			<title code="0x01000e">ダルゾン帝国</title>
			<title code="0x01000f">モンスターバトル</title>
			<title code="0x000010">エンドタイトル (エンディング)</title>
			<title code="0x010011">悲劇のテーマ</title>
			<title code="0x010012">ファイナルシューティング</title>
			<title code="0x010013">ショッピング</title>
			<title code="0x010014">きずな</title>
			<title code="0x010015">苦闘の果て</title>
			<title code="0x000018">ファンファーレ</title>
			<title code="0x000019">ファンファーレ2</title>
			<title code="0x000016">効果音</title>
			<title code="0x000017">効果音2</title>
		</titlelist>
  </game>
	<game>
		<name>[PC-88] Emerald Dragon (エメラルドドラゴン) (OPNA)</name>
		<driver type="opna">pc88</driver>
		<driveralias type="PC-88">glodia</driveralias>
		<options>
			<option name="mdata_addr" value="0x9000"/>
			<option name="mdata_size" value="0x3100"/>
			<option name="mfile_size" value="0x3100"/>
			<option name="use_vrtc"   value="0x01"/>
			<option name="clock_mul"  value="0x00"/>
		</options>
		<romlist archive="emdr88">
			<rom type="code" offset="0x0000">PATCH</rom>
			<rom type="code" offset="0x0100">EDMAIN</rom>
			<rom type="bgm" offset="0x00">AMOP6X</rom>
			<rom type="bgm" offset="0x01">AMOPX</rom>
			<rom type="bgm" offset="0x02">BGM4</rom>
			<rom type="bgm" offset="0x03">BIG</rom>
			<rom type="bgm" offset="0x04">BIGDEA</rom>
			<rom type="bgm" offset="0x05">EMBG01</rom>
			<rom type="bgm" offset="0x06">EMBG03</rom>
			<rom type="bgm" offset="0x07">EMBG04</rom>
			<rom type="bgm" offset="0x08">EMBG05</rom>
			<rom type="bgm" offset="0x09">EMBGD</rom>
			<rom type="bgm" offset="0x0a">EMBGG2</rom>
			<rom type="bgm" offset="0x0b">EMBGH</rom>
			<rom type="bgm" offset="0x0c">EMBGM</rom>
			<rom type="bgm" offset="0x0d">EMBGOP</rom>
			<rom type="bgm" offset="0x0e">EMED6A</rom>
			<rom type="bgm" offset="0x0f">EMEDA</rom>
			<rom type="bgm" offset="0x10">EMEF1</rom>
			<rom type="bgm" offset="0x11">EMFITB</rom>
			<rom type="bgm" offset="0x12">EMFITC</rom>
			<rom type="bgm" offset="0x13">EMFITD</rom>
			<rom type="bgm" offset="0x14">EMOP6A</rom>
			<rom type="bgm" offset="0x15">EMOP6B</rom>
			<rom type="bgm" offset="0x16">EMOP6C</rom>
			<rom type="bgm" offset="0x17">EMOP6D</rom>
			<rom type="bgm" offset="0x18">EMOP6E</rom>
			<rom type="bgm" offset="0x19">EMOPA</rom>
			<rom type="bgm" offset="0x1a">EMOPB</rom>
			<rom type="bgm" offset="0x1b">EMOPC</rom>
			<rom type="bgm" offset="0x1c">EMOPD</rom>
			<rom type="bgm" offset="0x1d">EMOPE</rom>
			<rom type="bgm" offset="0x1e">EMSHP1</rom>
			<rom type="bgm" offset="0x1f">EMSHP2</rom>
			<rom type="bgm" offset="0x20">EMSHP3</rom>
			<rom type="bgm" offset="0x21">EMSHP4</rom>
			<rom type="bgm" offset="0x22">EMVI01</rom>
			<rom type="bgm" offset="0x23">EMVI02</rom>
			<rom type="bgm" offset="0x24">EMVI03</rom>
			<rom type="bgm" offset="0x25">EMVI04</rom>
			<rom type="bgm" offset="0x26">EMVI05</rom>
			<rom type="bgm" offset="0x27">EMVI07</rom>
			<rom type="bgm" offset="0x28">EMVI08</rom>
			<rom type="bgm" offset="0x29">EMVI09</rom>
			<rom type="bgm" offset="0x2a">EMVI10</rom>
			<rom type="bgm" offset="0x2b">EMVI11</rom>
			<rom type="bgm" offset="0x2c">FAN1</rom>
		</romlist>
		<titlelist>
			<title code="0x80000014">オープニング 序曲</title>
			<title code="0x80000015">オープニング 天変地異</title>
			<title code="0x00000000">オープニング 回想１</title>
			<title code="0x00000016">オープニング 回想２</title>
			<title code="0x00000017">オープニング 永久なるもの</title>
			<title code="0x80000018">オープニング メインテーマ</title>
			<title code="0x00000005">城内</title>
			<title code="0x00000006">冒険開始</title>
			<title code="0x00000007">洞窟</title>
			<title code="0x00000008">試練</title>
			<title code="0x0000001f">ショップ２</title>
			<title code="0x0000001e">ショップ１</title>
			<title code="0x00000023">キャンドル</title>
			<title code="0x00000024">苦悩</title>
			<title code="0x00000026">アクティブ</title>
			<title code="0x00000021">ショップ３</title>
			<title code="0x00000028">再会(エンディング)</title>
			<title code="0x00000029">形勢不利</title>
			<title code="0x0000002a">ピンチ</title>
			<title code="0x0000002b">戦いの後に</title>
			<title code="0x0000000a">ロック</title>
			<title code="0x0000000b">街 １</title>
			<title code="0x0000000c">街 ２</title>
			<title code="0x00000009">黄昏</title>
			<title code="0x00000013">戦闘 １</title>
			<title code="0x00000012">戦闘 ２</title>
			<title code="0x00000011">戦闘 ３</title>
			<title code="0x8000000e">エンディング</title>
			<title code="0x00000002">テスタメント BGM2</title>
			<title code="0x00000003">テスタメント BOSS</title>
			<title code="0x80000004">効果音</title>
			<title code="0x0000000d">EMBGOP</title>
			<title code="0x80000010">EMEF1</title>
			<title code="0x00000020">EMSHP3</title>
			<title code="0x00000022">EMVI01</title>
			<title code="0x00000025">EMVI04</title>
			<title code="0x00000027">EMVI07</title>
			<title code="0x8000002c">FAN1</title>
		</titlelist>
	</game>
	<game>
		<name>[PC-88] Emerald Dragon (エメラルドドラゴン) (OPN)</name>
		<driver type="opn">pc88</driver>
		<driveralias type="PC-88">glodia</driveralias>
		<options>
			<option name="mdata_addr" value="0x9000"/>
			<option name="mdata_size" value="0x3100"/>
			<option name="mfile_size" value="0x3100"/>
			<option name="use_vrtc"   value="0x01"/>
			<option name="clock_mul"  value="0x00"/>
		</options>
		<romlist archive="emdr88">
			<rom type="code" offset="0x0000">PATCH</rom>
			<rom type="code" offset="0x0100">EDMAIN</rom>
			<rom type="bgm" offset="0x00">AMOP6X</rom>
			<rom type="bgm" offset="0x01">AMOPX</rom>
			<rom type="bgm" offset="0x02">BGM4</rom>
			<rom type="bgm" offset="0x03">BIG</rom>
			<rom type="bgm" offset="0x04">BIGDEA</rom>
			<rom type="bgm" offset="0x05">EMBG01</rom>
			<rom type="bgm" offset="0x06">EMBG03</rom>
			<rom type="bgm" offset="0x07">EMBG04</rom>
			<rom type="bgm" offset="0x08">EMBG05</rom>
			<rom type="bgm" offset="0x09">EMBGD</rom>
			<rom type="bgm" offset="0x0a">EMBGG2</rom>
			<rom type="bgm" offset="0x0b">EMBGH</rom>
			<rom type="bgm" offset="0x0c">EMBGM</rom>
			<rom type="bgm" offset="0x0d">EMBGOP</rom>
			<rom type="bgm" offset="0x0e">EMED6A</rom>
			<rom type="bgm" offset="0x0f">EMEDA</rom>
			<rom type="bgm" offset="0x10">EMEF1</rom>
			<rom type="bgm" offset="0x11">EMFITB</rom>
			<rom type="bgm" offset="0x12">EMFITC</rom>
			<rom type="bgm" offset="0x13">EMFITD</rom>
			<rom type="bgm" offset="0x14">EMOP6A</rom>
			<rom type="bgm" offset="0x15">EMOP6B</rom>
			<rom type="bgm" offset="0x16">EMOP6C</rom>
			<rom type="bgm" offset="0x17">EMOP6D</rom>
			<rom type="bgm" offset="0x18">EMOP6E</rom>
			<rom type="bgm" offset="0x19">EMOPA</rom>
			<rom type="bgm" offset="0x1a">EMOPB</rom>
			<rom type="bgm" offset="0x1b">EMOPC</rom>
			<rom type="bgm" offset="0x1c">EMOPD</rom>
			<rom type="bgm" offset="0x1d">EMOPE</rom>
			<rom type="bgm" offset="0x1e">EMSHP1</rom>
			<rom type="bgm" offset="0x1f">EMSHP2</rom>
			<rom type="bgm" offset="0x20">EMSHP3</rom>
			<rom type="bgm" offset="0x21">EMSHP4</rom>
			<rom type="bgm" offset="0x22">EMVI01</rom>
			<rom type="bgm" offset="0x23">EMVI02</rom>
			<rom type="bgm" offset="0x24">EMVI03</rom>
			<rom type="bgm" offset="0x25">EMVI04</rom>
			<rom type="bgm" offset="0x26">EMVI05</rom>
			<rom type="bgm" offset="0x27">EMVI07</rom>
			<rom type="bgm" offset="0x28">EMVI08</rom>
			<rom type="bgm" offset="0x29">EMVI09</rom>
			<rom type="bgm" offset="0x2a">EMVI10</rom>
			<rom type="bgm" offset="0x2b">EMVI11</rom>
			<rom type="bgm" offset="0x2c">FAN1</rom>
		</romlist>
		<titlelist>
			<title code="0x80000019">オープニング 序曲</title>
			<title code="0x8000001a">オープニング 天変地異</title>
			<title code="0x00000001">オープニング 回想１</title>
			<title code="0x0000001b">オープニング 回想２</title>
			<title code="0x0000001c">オープニング 永久なるもの</title>
			<title code="0x8000001d">オープニング メインテーマ</title>
			<title code="0x00000005">城内</title>
			<title code="0x00000006">冒険開始</title>
			<title code="0x00000007">洞窟</title>
			<title code="0x00000008">試練</title>
			<title code="0x0000001f">ショップ１</title>
			<title code="0x0000001e">ショップ２</title>
			<title code="0x00000023">キャンドル</title>
			<title code="0x00000024">苦悩</title>
			<title code="0x00000026">アクティブ</title>
			<title code="0x00000021">ショップ３</title>
			<title code="0x00000028">再会(エンディング)</title>
			<title code="0x00000029">形勢不利</title>
			<title code="0x0000002a">ピンチ</title>
			<title code="0x0000002b">戦いの後に</title>
			<title code="0x0000000a">ロック</title>
			<title code="0x0000000b">街 １</title>
			<title code="0x0000000c">街 ２</title>
			<title code="0x00000009">黄昏</title>
			<title code="0x00000013">戦闘 １</title>
			<title code="0x00000012">戦闘 ２</title>
			<title code="0x00000011">戦闘 ３</title>
			<title code="0x8000000f">エンディング</title>
			<title code="0x00000002">テスタメント BGM2</title>
			<title code="0x00000003">テスタメント BOSS</title>
			<title code="0x80000004">効果音</title>
			<title code="0x0000000d">EMBGOP</title>
			<title code="0x80000010">EMEF1</title>
			<title code="0x00000020">EMSHP3</title>
			<title code="0x00000022">EMVI01</title>
			<title code="0x00000025">EMVI04</title>
			<title code="0x00000027">EMVI07</title>
			<title code="0x8000002c">FAN1</title>
		</titlelist>
	</game>
	<game>
		<name>[PC-88] Emerald Dragon Music Disc (エメラルドドラゴン ミュージックディスク) (OPNA)</name>
		<driver type="opna">pc88</driver>
		<driveralias type="PC-88">glodia</driveralias>
		<options>
			<option name="mdata_addr" value="0x9000"/>
			<option name="mdata_size" value="0x3100"/>
			<option name="mfile_size" value="0x3100"/>
			<option name="use_vrtc"   value="0x01"/>
			<option name="clock_mul"  value="0x00"/>
		</options>
		<romlist archive="emdr88md">
			<rom type="code" offset="0x0000">PATCH</rom>
			<rom type="code" offset="0x0100">EDMAIN</rom>
			<rom type="bgm" offset="0x00">AMOP6X</rom>
			<rom type="bgm" offset="0x01">AMOPX</rom>
			<rom type="bgm" offset="0x02">EMBG01</rom>
			<rom type="bgm" offset="0x03">EMBG03</rom>
			<rom type="bgm" offset="0x04">EMBG04</rom>
			<rom type="bgm" offset="0x05">EMBG05</rom>
			<rom type="bgm" offset="0x06">EMBG07</rom>
			<rom type="bgm" offset="0x07">EMBG08</rom>
			<rom type="bgm" offset="0x08">EMBG09</rom>
			<rom type="bgm" offset="0x09">EMBGD</rom>
			<rom type="bgm" offset="0x0a">EMBGG2</rom>
			<rom type="bgm" offset="0x0b">EMBGH</rom>
			<rom type="bgm" offset="0x0c">EMBGM</rom>
			<rom type="bgm" offset="0x0d">EMBGOP</rom>
			<rom type="bgm" offset="0x0e">EMED6A</rom>
			<rom type="bgm" offset="0x0f">EMEDA</rom>
			<rom type="bgm" offset="0x10">EMEF1</rom>
			<rom type="bgm" offset="0x11">EMFITA</rom>
			<rom type="bgm" offset="0x12">EMFITB</rom>
			<rom type="bgm" offset="0x13">EMFITC</rom>
			<rom type="bgm" offset="0x14">EMFITD</rom>
			<rom type="bgm" offset="0x15">EMOP6A</rom>
			<rom type="bgm" offset="0x16">EMOP6B</rom>
			<rom type="bgm" offset="0x17">EMOP6C</rom>
			<rom type="bgm" offset="0x18">EMOP6D</rom>
			<rom type="bgm" offset="0x19">EMOP6E</rom>
			<rom type="bgm" offset="0x1a">EMOPA</rom>
			<rom type="bgm" offset="0x1b">EMOPB</rom>
			<rom type="bgm" offset="0x1c">EMOPC</rom>
			<rom type="bgm" offset="0x1d">EMOPD</rom>
			<rom type="bgm" offset="0x1e">EMOPE</rom>
			<rom type="bgm" offset="0x1f">EMSHP1</rom>
			<rom type="bgm" offset="0x20">EMSHP2</rom>
			<rom type="bgm" offset="0x21">EMSHP3</rom>
			<rom type="bgm" offset="0x22">EMSHP4</rom>
			<rom type="bgm" offset="0x23">EMVI01</rom>
			<rom type="bgm" offset="0x24">EMVI02</rom>
			<rom type="bgm" offset="0x25">EMVI03</rom>
			<rom type="bgm" offset="0x26">EMVI04</rom>
			<rom type="bgm" offset="0x27">EMVI05</rom>
			<rom type="bgm" offset="0x28">EMVI07</rom>
			<rom type="bgm" offset="0x29">EMVI08</rom>
			<rom type="bgm" offset="0x2a">EMVI09</rom>
			<rom type="bgm" offset="0x2b">EMVI10</rom>
			<rom type="bgm" offset="0x2c">EMVI11</rom>
			<rom type="bgm" offset="0x2d">EMVI64</rom>
		</romlist>
		<titlelist>
			<title code="0x80000015">オープニング 序曲</title>
			<title code="0x80000016">オープニング 天変地異</title>
			<title code="0x00000000">オープニング 回想１</title>
			<title code="0x00000017">オープニング 回想２</title>
			<title code="0x00000018">オープニング 永久なるもの</title>
			<title code="0x80000019">オープニング メインテーマ</title>
			<title code="0x00000002">城内</title>
			<title code="0x00000003">冒険開始</title>
			<title code="0x00000004">洞窟</title>
			<title code="0x00000005">試練</title>
			<title code="0x00000020">ショップ１</title>
			<title code="0x0000001f">ショップ２</title>
			<title code="0x00000024">キャンドル</title>
			<title code="0x00000025">苦悩</title>
			<title code="0x00000027">アクティブ</title>
			<title code="0x00000022">ショップ３</title>
			<title code="0x00000029">再会(エンディング)</title>
			<title code="0x0000002a">形勢不利</title>
			<title code="0x0000002b">ピンチ</title>
			<title code="0x0000002c">戦いの後に</title>
			<title code="0x0000000a">ロック</title>
			<title code="0x0000000b">街 １</title>
			<title code="0x0000000c">街 ２</title>
			<title code="0x00000009">黄昏</title>
			<title code="0x00000014">戦闘 １</title>
			<title code="0x00000013">戦闘 ２</title>
			<title code="0x00000012">戦闘 ３</title>
			<title code="0x8000000e">エンディング</title>
			<title code="0x00000026">EMVI04</title>
			<title code="0x00000006">EMBG07</title>
			<title code="0x00000007">EMBG08</title>
			<title code="0x00000008">EMBG09</title>
			<title code="0x0000000d">EMBGOP</title>
			<title code="0x80000010">EMEF1</title>
			<title code="0x00000011">EMFITA</title>
			<title code="0x00000023">EMVI01</title>
			<title code="0x00000028">EMVI07</title>
			<title code="0x0000002d">EMVI64</title>
		</titlelist>
	</game>
	<game>
		<name>[PC-88] Emerald Dragon Music Disc (エメラルドドラゴン ミュージックディスク) (OPN)</name>
		<driver type="opn">pc88</driver>
		<driveralias type="PC-88">glodia</driveralias>
		<options>
			<option name="mdata_addr" value="0x9000"/>
			<option name="mdata_size" value="0x3100"/>
			<option name="mfile_size" value="0x3100"/>
			<option name="use_vrtc"   value="0x01"/>
			<option name="clock_mul"  value="0x00"/>
		</options>
		<romlist archive="emdr88md">
			<rom type="code" offset="0x0000">PATCH</rom>
			<rom type="code" offset="0x0100">EDMAIN</rom>
			<rom type="bgm" offset="0x00">AMOP6X</rom>
			<rom type="bgm" offset="0x01">AMOPX</rom>
			<rom type="bgm" offset="0x02">EMBG01</rom>
			<rom type="bgm" offset="0x03">EMBG03</rom>
			<rom type="bgm" offset="0x04">EMBG04</rom>
			<rom type="bgm" offset="0x05">EMBG05</rom>
			<rom type="bgm" offset="0x06">EMBG07</rom>
			<rom type="bgm" offset="0x07">EMBG08</rom>
			<rom type="bgm" offset="0x08">EMBG09</rom>
			<rom type="bgm" offset="0x09">EMBGD</rom>
			<rom type="bgm" offset="0x0a">EMBGG2</rom>
			<rom type="bgm" offset="0x0b">EMBGH</rom>
			<rom type="bgm" offset="0x0c">EMBGM</rom>
			<rom type="bgm" offset="0x0d">EMBGOP</rom>
			<rom type="bgm" offset="0x0e">EMED6A</rom>
			<rom type="bgm" offset="0x0f">EMEDA</rom>
			<rom type="bgm" offset="0x10">EMEF1</rom>
			<rom type="bgm" offset="0x11">EMFITA</rom>
			<rom type="bgm" offset="0x12">EMFITB</rom>
			<rom type="bgm" offset="0x13">EMFITC</rom>
			<rom type="bgm" offset="0x14">EMFITD</rom>
			<rom type="bgm" offset="0x15">EMOP6A</rom>
			<rom type="bgm" offset="0x16">EMOP6B</rom>
			<rom type="bgm" offset="0x17">EMOP6C</rom>
			<rom type="bgm" offset="0x18">EMOP6D</rom>
			<rom type="bgm" offset="0x19">EMOP6E</rom>
			<rom type="bgm" offset="0x1a">EMOPA</rom>
			<rom type="bgm" offset="0x1b">EMOPB</rom>
			<rom type="bgm" offset="0x1c">EMOPC</rom>
			<rom type="bgm" offset="0x1d">EMOPD</rom>
			<rom type="bgm" offset="0x1e">EMOPE</rom>
			<rom type="bgm" offset="0x1f">EMSHP1</rom>
			<rom type="bgm" offset="0x20">EMSHP2</rom>
			<rom type="bgm" offset="0x21">EMSHP3</rom>
			<rom type="bgm" offset="0x22">EMSHP4</rom>
			<rom type="bgm" offset="0x23">EMVI01</rom>
			<rom type="bgm" offset="0x24">EMVI02</rom>
			<rom type="bgm" offset="0x25">EMVI03</rom>
			<rom type="bgm" offset="0x26">EMVI04</rom>
			<rom type="bgm" offset="0x27">EMVI05</rom>
			<rom type="bgm" offset="0x28">EMVI07</rom>
			<rom type="bgm" offset="0x29">EMVI08</rom>
			<rom type="bgm" offset="0x2a">EMVI09</rom>
			<rom type="bgm" offset="0x2b">EMVI10</rom>
			<rom type="bgm" offset="0x2c">EMVI11</rom>
		<!--	<rom type="bgm" offset="0x2d">EMVI64</rom> -->
		</romlist>
		<titlelist>
			<title code="0x8000001a">オープニング 序曲</title>
			<title code="0x8000001b">オープニング 天変地異</title>
			<title code="0x00000001">オープニング 回想１</title>
			<title code="0x0000001c">オープニング 回想２</title>
			<title code="0x0000001d">オープニング 永久なるもの</title>
			<title code="0x8000001e">オープニング メインテーマ</title>
			<title code="0x00000002">城内</title>
			<title code="0x00000003">冒険開始</title>
			<title code="0x00000004">洞窟</title>
			<title code="0x00000005">試練</title>
			<title code="0x00000020">ショップ１</title>
			<title code="0x0000001f">ショップ２</title>
			<title code="0x00000024">キャンドル</title>
			<title code="0x00000025">苦悩</title>
			<title code="0x00000027">アクティブ</title>
			<title code="0x00000022">ショップ３</title>
			<title code="0x00000029">再会(エンディング)</title>
			<title code="0x0000002a">形勢不利</title>
			<title code="0x0000002b">ピンチ</title>
			<title code="0x0000002c">戦いの後に</title>
			<title code="0x0000000a">ロック</title>
			<title code="0x0000000b">街 １</title>
			<title code="0x0000000c">街 ２</title>
			<title code="0x00000009">黄昏</title>
			<title code="0x00000014">戦闘 １</title>
			<title code="0x00000013">戦闘 ２</title>
			<title code="0x00000012">戦闘 ３</title>
			<title code="0x8000000f">エンディング</title>
			<title code="0x00000026">EMVI04</title>
			<title code="0x00000006">EMBG07</title>
			<title code="0x00000007">EMBG08</title>
			<title code="0x00000008">EMBG09</title>
			<title code="0x0000000d">EMBGOP</title>
			<title code="0x80000010">EMEF1</title>
			<title code="0x00000011">EMFITA</title>
			<title code="0x00000023">EMVI01</title>
			<title code="0x00000028">EMVI07</title>
		<!--	<title code="0x0000002d">EMVI64 : </title> -->
		</titlelist>
	</game>
	<game>
		<name>[PC-98] Emerald Dragon (エメラルドドラゴン)</name>
		<driver type="opn">pc98vx</driver>
		<driveralias type="PC-98">glodia</driveralias>
		<options>
			<option name="bootcs" value="0x0060"/>
			<option name="bootip" value="0x0000"/>
			<option name="filesize" value="0x2000"/>
			<option name="dataaddr" value="0x15f10"/>
			<option name="clockmul" value="0x04"/>
			<option name="datamax"  value="0x2a"/>
			<option name="fm_mix"   value="19"/>
			<option name="ssg_mix"  value="0"/>
		</options>
		<romlist archive="emdr98">
			<rom type="code" offset="0x00600">emdr98.bin</rom>
			<rom type="code" offset="0x12000">MAIN</rom>
			<rom type="bgm" offset="0x01">AMOPX.S</rom>
			<rom type="bgm" offset="0x02">BGM4.S</rom>
			<rom type="bgm" offset="0x03">BGM5.S</rom>
			<rom type="bgm" offset="0x04">BIG.S</rom>
			<rom type="bgm" offset="0x05">EMBG01.S</rom>
			<rom type="bgm" offset="0x06">EMBG03.S</rom>
			<rom type="bgm" offset="0x07">EMBG04.S</rom>
			<rom type="bgm" offset="0x08">EMBG05.S</rom>
			<rom type="bgm" offset="0x09">EMBGD.S</rom>
			<rom type="bgm" offset="0x0a">EMBGG2.S</rom>
			<rom type="bgm" offset="0x0b">EMBGH.S</rom>
			<rom type="bgm" offset="0x0c">EMBGM.S</rom>
			<rom type="bgm" offset="0x0d">EMBGOP.S</rom>
			<rom type="bgm" offset="0x0e">EMEDA.S</rom>
			<rom type="bgm" offset="0x0f">EMEF1.S</rom>
			<rom type="bgm" offset="0x10">EMFITA.S</rom>
			<rom type="bgm" offset="0x11">EMFITB.S</rom>
			<rom type="bgm" offset="0x12">EMFITC.S</rom>
			<rom type="bgm" offset="0x13">EMFITD.S</rom>
			<rom type="bgm" offset="0x14">EMOPA.S</rom>
			<rom type="bgm" offset="0x15">EMOPB.S</rom>
			<rom type="bgm" offset="0x16">EMOPC.S</rom>
			<rom type="bgm" offset="0x17">EMOPD.S</rom>
			<rom type="bgm" offset="0x18">EMOPE.S</rom>
			<rom type="bgm" offset="0x19">EMSHP1.S</rom>
			<rom type="bgm" offset="0x1a">EMSHP2.S</rom>
			<rom type="bgm" offset="0x1b">EMSHP3.S</rom>
			<rom type="bgm" offset="0x1c">EMSHP4.S</rom>
			<rom type="bgm" offset="0x1d">EMVI01.S</rom>
			<rom type="bgm" offset="0x1e">EMVI02.S</rom>
			<rom type="bgm" offset="0x1f">EMVI03.S</rom>
			<rom type="bgm" offset="0x20">EMVI04.S</rom>
			<rom type="bgm" offset="0x21">EMVI05.S</rom>
			<rom type="bgm" offset="0x22">EMVI07.S</rom>
			<rom type="bgm" offset="0x23">EMVI08.S</rom>
			<rom type="bgm" offset="0x24">EMVI09.S</rom>
			<rom type="bgm" offset="0x25">EMVI10.S</rom>
			<rom type="bgm" offset="0x26">EMVI11.S</rom>
			<rom type="bgm" offset="0x27">EMVI64.S</rom>
			<rom type="bgm" offset="0x28">FAN1.S</rom>
			<rom type="bgm" offset="0x29">FAN3.S</rom>
		</romlist>
		<titlelist>
			<title code="0x800014">オープニング 序曲</title>
			<title code="0x800015">オープニング 天変地異</title>
			<title code="0x000001">オープニング 回想１</title>
			<title code="0x000016">オープニング 回想２</title>
			<title code="0x000017">オープニング 永久なるもの</title>
			<title code="0x800018">オープニング メインテーマ</title>
			<title code="0x000005">城内</title>
			<title code="0x000006">冒険開始</title>
			<title code="0x000007">洞窟</title>
			<title code="0x000008">試練</title>
			<title code="0x00001a">ショップ１</title>
			<title code="0x000019">ショップ２</title>
			<title code="0x00001e">キャンドル</title>
			<title code="0x00001f">苦悩</title>
			<title code="0x000021">アクティブ</title>
			<title code="0x00001c">ショップ３</title>
			<title code="0x000023">再会 (エンディング)</title>
			<title code="0x000024">形勢不利</title>
			<title code="0x000025">ピンチ</title>
			<title code="0x000026">戦いの後に</title>
			<title code="0x00000a">ロック</title>
			<title code="0x00000b">街 １</title>
			<title code="0x00000c">街 ２</title>
			<title code="0x000009">黄昏</title>